create extension if not exists pgcrypto;
create table if not exists users(
 id uuid primary key default gen_random_uuid(),
 telegram_id bigint unique not null,
 username text,
 first_name text not null default 'Miner',
 last_name text,
 balance numeric(20,6) not null default 0,
 referrals integer not null default 0,
 streak integer not null default 0,
 last_mined_at timestamptz,
 created_at timestamptz not null default now()
);
create table if not exists mining_events(
 id bigint generated by default as identity primary key,
 user_id uuid references users(id) on delete cascade,
 reward numeric(20,6) not null,
 created_at timestamptz not null default now()
);
create index if not exists mining_events_user_idx on mining_events(user_id,created_at desc);
alter table users enable row level security;
alter table mining_events enable row level security;
